- mailu/Chart.yaml
- mailu/templates/admin.yaml
- mailu/templates/clamav.yaml
- mailu/templates/dovecot.yaml
- mailu/templates/front.yaml
- mailu/templates/postfix.yaml
- mailu/templates/redis.yaml
- mailu/templates/roundcube.yaml
- mailu/templates/rspamd.yaml
- mailu/values.yaml
Enhancement to the chart to allow resource limits to be configurable instead of only static
> Adding configurable resource limits

- mailu/Chart.yaml
- mailu/templates/admin.yaml
- mailu/templates/clamav.yaml
- mailu/templates/dovecot.yaml
- mailu/templates/front.yaml
- mailu/templates/postfix.yaml
- mailu/templates/redis.yaml
- mailu/templates/roundcube.yaml
- mailu/templates/rspamd.yaml
Porting Mailu/Mailu#1241 to the helm-charts repo
> Change extensions/v1beta to apps/v1 to be compliant with Kubernetes 1.16

- mailu/templates/pvc.yaml
- mailu/values.yaml
This adds the ability to use a storageClass for dynamic provisioning opposed to only supporting hostPath
> Adding storageClass for dynamic storage provisioning

- mailu/README.md
I noticed I introduced an error in the `REAME.md` file with https://github.com/Mailu/helm-charts/pull/17 after fixing the review comments.
This PR fixes it.
> Fix error in README.md about the storageClass parameter

- mailu/README.md
think there is a confusion about parts of mail address
> docu change before/after at initial account

- mailu/templates/front.yaml
Not sure how this happened, maybe when I merged. Updates #35
> Fix bad checkin

- mailu/templates/admin.yaml
- mailu/templates/clamav.yaml
- mailu/templates/dovecot.yaml
- mailu/templates/front.yaml
- mailu/templates/mysql.yaml
- mailu/templates/postfix.yaml
- mailu/templates/redis.yaml
- mailu/templates/roundcube.yaml
- mailu/templates/rspamd.yaml
- mailu/templates/webdav.yaml
- mailu/values.yaml
This PR add ability to set tolerations and affinity for pods
> add ability to set tolerations and affinity for pods

- mailu/README.md
The old ways don't work anymore. Fixed the helm-chart call on deploying, added info on how to create the values file, and added info on how to delete deployed helm-chart.
> Documentation update

- mailu/Chart.yaml
- mailu/README.md
- mailu/templates/certificate.yaml
- mailu/values.yaml
Hey,
Cleanner PR for only certmanager removal
Following #98  everything is now correctly split in 4 distinct PR
Regards,
> Removing cert Manager Dependency

- mailu/templates/fetchmail.yaml
Hello,
Spliting PR as discussed in #98
> Correct templating fetchmail

- mailu/templates/front.yaml
- mailu/values.yaml
Please let me know if anything is missing.
> add option for loadBalancerIP

- mailu/templates/postfix/configmap.yaml
> fix: postfix-overrides ConfigMap will never render #234

- mailu/templates/_secrets.tpl
- mailu/templates/secret-external-relay.yaml
> fix: fixed encoding of relayuser and relaypassword

- mailu/templates/_secrets.tpl
- mailu/templates/fetchmail/deployment.yaml
- mailu/templates/secret-external-relay.yaml
> fix: fixed typo in fetchmail deployment

- mailu/templates/fetchmail/deployment.yaml
- mailu/templates/front/service-external.yaml
> fix: fixed typo when external service set to NodePort

- mailu/README.md
- mailu/templates/envvars-configmap.yaml
- mailu/values.yaml
> feat: Add `proxyAuth` section to values to configure `PROXY_AUTH_*` env vars

- README.md
- mailu/README.md
This PR makes the shields/badges shown in the README files dynamic.
It uses the values from the first mailu entry in the `index.yaml` file.
> feat: dynamic shields

- mailu/Chart.lock
- mailu/Chart.yaml
> feat: update Bitnami charts dependencies

- .github/workflows/lint-and-test.yaml
- mailu/README.md
- mailu/templates/admin/deployment.yaml
- mailu/templates/clamav/statefulset.yaml
- mailu/templates/dovecot/deployment.yaml
- mailu/templates/fetchmail/deployment.yaml
- mailu/templates/postfix/deployment.yaml
- mailu/templates/webdav/deployment.yaml
- mailu/templates/webmail/deployment.yaml
- mailu/values.yaml
> fix: fixed probes

- mailu/templates/envvars-configmap.yaml
Adding `MAILU_HELM_CHART=true` to all containers environment variable as a long term fix for #309 
This will need a change in Mailu code as well.
> feat: add MAILU_HELM_CHART environment variable

- mailu/templates/admin/deployment.yaml
- mailu/templates/clamav/statefulset.yaml
- mailu/templates/dovecot/deployment.yaml
- mailu/templates/fetchmail/deployment.yaml
- mailu/templates/front/deployment.yaml
- mailu/templates/oletools/deployment.yaml
- mailu/templates/postfix/deployment.yaml
- mailu/templates/rspamd/deployment.yaml
- mailu/templates/webdav/deployment.yaml
- mailu/templates/webmail/deployment.yaml
- mailu/values.yaml
in order to allow users to inject sidecar-containers to each component
> feat: add extraContainers to helm chart 

- mailu/README.md
- mailu/values.yaml
Fix a small typo / imprecissions in the Chart README
> fix: Fix Chart readme typos

- charts/mailu/README.md
- charts/mailu/templates/front/service-external.yaml
- charts/mailu/values.yaml
> feat(externalService): allow to set labels

- charts/mailu/templates/dovecot/servicemonitor.yaml
- charts/mailu/templates/rspamd/servicemonitor.yaml
> fix(serviceMonitor): labelSelector declaration
