Mailu/helm-charts

mailu/templates/admin.yaml

The current admin.yaml references .Values.database.host while the path should be .Values.database.mysql.host
Additionally, I wrapped the include "mailu.fullname" usage in an else-branch

Fix external database not being used

---

mailu/README.md
mailu/templates/front.yaml
mailu/templates/ingress.yaml
mailu/values.yaml

PR provides ability for web endpoints to be TLS protected via nginx instance provided in `front` container. Also add ability to change DNS root domain for an installation from `cluster.local`.

Add ability to run TLS webmail without external NGINX.

---

mailu/README.md
mailu/helm-lint-values.yaml
mailu/templates/pvc.yaml
mailu/values.yaml

This commit allows specifying annotations for the PVC.
This is useful for example to add the annotation for helm to keep the PVC when deleting the chart in order to avoid accidentally losing the data.

add ability specifying annotations for the PVC

---

mailu/README.md
mailu/templates/ingress.yaml
mailu/values.yaml

This commit allows specifying annotations for the ingress.
This is useful for example to customize the NGINX controller configuration.
Also this feature was asked here: https://github.com/Mailu/helm-charts/pull/26#discussion_r397964807

add ability specifying annotations for the ingress

---

mailu/Chart.yaml
mailu/README.md
mailu/templates/front.yaml
mailu/templates/mysql.yaml
mailu/templates/roundcube.yaml
mailu/values.yaml

This PR adds support for selectable database type for roundcube. It defaults to sqlite (indepenent of which database type mailu uses) for backward compatibility.

Add mysql support for roundcube

---

mailu/templates/ingress.yaml

If you specify multiple Hosts the Templates renders multiple "rules"-Section. But there should only be one rules-Option and then multiple Host-Sections:
See Kube-Docs: https://kubernetes.io/docs/concepts/services-networking/ingress/#name-based-virtual-hosting
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
name: name-virtual-host-ingress
spec:
rules:
- host: foo.bar.com
http:
paths:
- backend:
serviceName: service1
servicePort: 80
- host: bar.foo.com
http:
paths:
- backend:
serviceName: service2
servicePort: 80
```
Becaus of this Issue only the last specified Host is reachable from the outside.

Fix Multi Host Bug

---

mailu/templates/roundcube.yaml
mailu/values.yaml

Fix for Postgres database parameter indentation error in Roundcube deployment.
Nicer chart values comment indentation in values.yaml.
@micw This fixes an indentation error in the Postgres Database support just merged.

Fix for Postgres database parameter indentation error in Roundcube deployment

---

mailu/templates/dovecot.yaml
mailu/values.yaml

Not everyone may need Dovecot (IMAP services), so this component should be possible to disable.
For example, in my use-case, I only need to be able to receive emails on some domains, have some mail aliases and need to be able to send emails via SMTP.

Dovecot made optional

---

mailu/templates/postfix.yaml
mailu/values.yaml

Hi,
Mailu supports setting a RELAYHOST along with login credentials via the environment variables.
This patch/PR adds that basic usage to the Helm-chart

Add RELAYHOST support

---

mailu/README.md
mailu/templates/front.yaml
mailu/values.yaml

This fixes #46
It introduces a variable `front.controller.kind` which can be `Deployment` (default) or `DaemonSet`.
Depending on your environment you might want to shedule "only one pod" (`Deployment`) or "one pod per node" (`DaemonSet`) for the `front` nginx pod(s).
A `DaemonSet` can e.g. be usefull if you have multiple DNS entries / IPs in your MX record and want `front` to be reachable on every IP.

add config option to use Deployment/DaemonSet for front pod(s)

---

mailu/templates/admin.yaml
mailu/values.yaml

At least one pod should be able to get pod annotations in order to allow utilities like Velero identify the 'data' persistent volume for backup (Velero reads pod annotations to discover backup requests)
Pod annotations for ALL pods may be superfluous and may make the chart values more complex unnecessarily so I didn't add the podAnnotations for all of them.

Support podAnnotations on the admin pod

---

mailu/templates/admin.yaml
mailu/templates/clamav.yaml
mailu/templates/combined.yaml
mailu/templates/dovecot.yaml
mailu/templates/front.yaml
mailu/templates/mysql.yaml
mailu/templates/postfix.yaml
mailu/templates/pvc.yaml
mailu/templates/redis.yaml
mailu/templates/roundcube.yaml
mailu/templates/rspamd.yaml
mailu/templates/webdav.yaml
mailu/values.yaml

This PR allows a deployer to install the chart with 
- `admin` and `rspamd` charts merged, making the `subPath: /dkim` only used by a single pod
- Individual non-shared PVCs for the different pods
It's one step on cleanly allowing the changes in #39 to be realized.

Step on #39: Allow for merged pod containing both rspamd and admin

---

mailu/templates/roundcube.yaml

It is currently impossible to specify an external mysql database with roundcube enabled, as the chart will always take the internal database hostname (missing else statement in roundcube.yaml template)

Fix bug with roundcube and external mysql database

---

mailu/README.md
mailu/helm-lint-values.yaml
mailu/templates/fetchmail.yaml
mailu/values.yaml

This adds fetchmail support to the chart.
It is disabled by default-
Included are also parameters to tune the `FETCHMAIL_DELAY`.

add fetchmail deployment

---

mailu/Chart.yaml
mailu/templates/postfix.yaml

When using rollingupdate, postfix remains stuck. Setting the strategy to Recreate make it start normally.

Change update strategy to recreate

---

mailu/Chart.yaml
mailu/templates/certificate.yaml

While moving from default Helm3 to ArgoCD i experienced, that the value is not consitent with the Kubernetes API Object.
This will result in a faulty state in ArgoCD because the Manifest always differs from the Kubernetes API Object

make Certificate Renew value consistent with Kubernetes API Object

---

mailu/Chart.yaml
mailu/templates/ingress.yaml

The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of kubernetes v1.22.
The networking.k8s.io/v1 API version, available since kubernetes v1.19.
Updated manifest from use API 'networking.k8s.io/v1beta1' to use 'networking.k8s.io/v1'
Ref: https://kubernetes.io/docs/reference/using-api/deprecation-guide/ -> Ingress

Change API from 'networking.k8s.io/v1beta1' to 'networking.k8s.io/v1'

---

mailu/templates/ingress.yaml

Hi, the changes in https://github.com/Mailu/helm-charts/pull/106 are invalid: 
`error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service.port): invalid type for io.k8s.api.networking.v1.ServiceBackendPort: got "integer", expected "map"`

fix ingress service port

---

mailu/templates/dovecot.yaml
mailu/templates/postfix.yaml
mailu/values.yaml

Some runtimes, such as CRI-O, require granting additional capabilities to the container in order for `chroot` syscalls to success. This PR allows specifying the securityContext for the postfix and dovecot containers, which rely on these syscalls to work properly.

postfix,dovecot: allow defining container.securityContext

---

mailu/templates/ingress.yaml
mailu/values.yaml

Ingress controllers are starting to ignore annotations as a means to define the class name. For example, `ingress-nginx` now ignores annotations by default.
This simple PR allows to specify `ingressClassName` from the values file.

ingress: allow defining ingressClassName

---

mailu/templates/postfix.yaml

Use existing secret for postfix relay if provided

Enable the use of an existing secret for postfix relay if provided

---

mailu/templates/clamav.yaml
mailu/templates/rspamd-clamav-pvc.yml
mailu/templates/rspamd.yaml
mailu/values.yaml

Hi,
according to https://github.com/Mailu/helm-charts/blob/master/mailu/values.yaml#L335 rspamd and clamav needs a shared volume.
However this isn't the case and also the volume is already split into "subvolumes" by using subPaths. So clamav can't access rspamd data and vice versa.
Also I don't see any other technical reason for this since all communication between rspamd and clamav is done over network since at least 2018. AFAIK the clamav integration within rspamd never used the disk to share mail data for scanning.
This PR adds an option **rspamd_clamav_persistence.single_pvc** which is set to **false** by default. This keeps everything like it's now (i.e. keeps the shared volume).
Setting this value to **true** will create two PVC **mailu-clamav** and **mailu-rspamd**. With seperate …

Add option for seperate PVCs for rspamd/clamav

---

mailu/README.md
mailu/test.yml
mailu/values.yaml

Replace all instances of `cert-manager.io/v1alpha2` with `cert-manager.io/v1` (fixes #159)

Fix #159 - Incorrect version of Cert-Manager

---

mailu/README.md
mailu/templates/admin.yaml
mailu/templates/dovecot.yaml
mailu/templates/roundcube.yaml

This allow setting a secret key ref instead of directly passing in a
secret in.
for example with the secret
```yaml
apiVersion: v1
kind: Secret
metadata:
name: mailu-secret
data:
my-key: YmFyCg==
```
it could be used from this chart like
```yaml
domain: mail.mydomain.com
hostnames:
- mail.mydomain.com
initialAccount:
domain: mail.mydomain.com
password: chang3m3!
username: mailadmin
logLevel: INFO
mail:
authRatelimit: 100/minute;3600/hour
messageSizeLimitInMegabytes: 200
persistence:
size: 100Gi
storageClass: fast
secretKeyRef:
name: mailu-secret
key: my-key
```

add secret key ref for SECRET_KEY env var

---

mailu/values.yaml

Current version is still 1.9.10 which causes issues with current coredns implementations. Mailu-admin 1.9.20 introtuced a patch to fix this.
See issue #144 
This bumps the version to the latest available mailu version 1.9.26 since later versions also include security fixes (openssl and zlib).

Bump version to latest mailu-1.9.26

---

mailu/Chart.yaml
mailu/README.md
mailu/templates/clamav.yaml
mailu/templates/fetchmail.yaml
mailu/templates/front.yaml
mailu/templates/redis.yaml
mailu/templates/roundcube.yaml
mailu/templates/rspamd.yaml
mailu/templates/webdav.yaml

The current setup is not usable in clusters that are using default scc: restricted. 
In this specific case, we need SYS_CHROOT in the Redis app which is not possible due to the default used SCC.
By adding security context to each application we are allowing users to define which SCC they want to use. 
The issue https://github.com/Mailu/helm-charts/issues/163 could be closed with this MR.

Add support for containerSecurityContext

---

mailu/README.md
mailu/templates/envvars-configmap.yaml
mailu/values.yaml

This PR adds the option to set the `WILDCARD_SENDERS` env var.
New configuration:
```yaml
wildcardSenders: []
```
Example:
```yaml
wildcardSenders:
- user1@example.com
- user2@example.com
```
Closes #148

feat: Added support for WILDCARD_SENDERS

---

mailu/README.md
mailu/templates/envvars-configmap.yaml
mailu/values.yaml

This PR add support to set the following environment variables:
- DEFER_ON_TLS_ERROR
- INBOUND_TLS_ENFORCE
- OUTBOUND_TLS_LEVEL
Added configuration options:
```yaml
tls:
outboundLevel: ""
deferOnError: ""
inboundEnforce: ""
```
Closes #151

feat: Add support for TLS settings

---

mailu/templates/_claims.tpl

Simply added the missing template in the same fashion as all other templates in `_claims.tpl`.
Closes #232

fix: Helm error when deploying with webdav.enabled=true because of missing template #232

---

mailu/templates/dovecot/deployment.yaml

```
dovecot:
readinessProbe:
enabled: false
```
was producing in dovecot development the readinessProbe config

fix: [dovecot] obey readinessProbe enable config

---

mailu/templates/_services.tpl

fix: fix redis service name when using Mailu as a subchart

---

mailu/templates/admin/deployment.yaml
mailu/templates/clamav/statefulset.yaml
mailu/templates/fetchmail/deployment.yaml
mailu/templates/front/deployment.yaml
mailu/templates/oletools/deployment.yaml
mailu/templates/postfix/deployment.yaml
mailu/templates/rspamd/deployment.yaml
mailu/templates/webdav/deployment.yaml
mailu/templates/webmail/deployment.yaml

This is the same fix as #250, but for other pods.
Example: the following config does not disable readiness probe for postfix as it should.
```yaml
postfix:
readinessProbe:
enabled: false
```

fix: readinessProbe.enabled has no effect

---

mailu/templates/_secrets.tpl
mailu/templates/envvars-configmap.yaml

This is to fix https://github.com/Mailu/helm-charts/issues/259 where you get:
```
Error: secret "mailu-roundcube" not found when "webmail.enabled" is false
```
Not sure if I need to bump the helm chart version, but happy to do so.

fix: only include roudcube secrets if webmail.enabled is set to true

---

mailu/README.md
mailu/templates/admin/deployment.yaml
mailu/templates/clamav/statefulset.yaml
mailu/templates/dovecot/deployment.yaml
mailu/templates/fetchmail/deployment.yaml
mailu/templates/front/deployment.yaml
mailu/templates/oletools/deployment.yaml
mailu/templates/postfix/deployment.yaml
mailu/templates/rspamd/deployment.yaml
mailu/templates/webdav/deployment.yaml
mailu/templates/webmail/deployment.yaml
mailu/values.yaml

Postfix and Dovecot sometimes need capabilities that some CRIs, such as cri-o, do not support by default, e.g. `SYS_CHROOT`. In these cases, if these capabilities are not added explicitly, postfix and dovecot won't start.
This commit adds `.Values.{postfix,dovecot}.containerSecurityContext` to values.yaml and to the corresponding templates.
This PR is effectively the same as https://github.com/Mailu/helm-charts/pull/125, which seems to have been lost in the 1.x migration.

feat: add securityContext and podSecurityContext options

---

mailu/Chart.yaml
mailu/templates/_helpers.tpl
mailu/templates/admin/deployment.yaml
mailu/templates/admin/service.yaml

Release notes: https://github.com/Mailu/Mailu/releases/tag/2.0.22
Update is retro-compatible with versions <2.0.22 (the admin container port will then be kept to port `80` instead of the new `8080`).
When setting `mailuVersion` or `admin.image.tag` to a non-valid semver, the chart will behave as if the version is >= 2.0.22 and use the port `8080` for the admin container.

feat: bump mailu version to 2.0.22

---

mailu/templates/NOTES.txt

Fixed kubectl command to retrieve the initial password.   
'get secrets' was included twice.

fix helmchart notes duplicate 'get secrets'

---

mailu/README.md
mailu/templates/clamav/statefulset.yaml
mailu/values.yaml

Mailu is now using the official clamav container, this PR updates the chart to make it work with that setup as well.
This is not retro-compatible, it only works with Mailu >= 2024.06

feat: Replace mailu clamav container with official container

---

mailu/Chart.yaml
mailu/README.md
mailu/templates/rspamd/deployment.yaml
mailu/templates/rspamd/pvc.yaml
mailu/templates/rspamd/service.yaml
mailu/values.yaml

this PR adds the enable flag to rspamd, as the value is by default "false" it skips the entire config if not set.
for example, the configmap to override settings was entierly skipped when i tried to upgrade

added flag to enable rspamd

---

mailu/README.md
mailu/ci/helm-lint-values.yaml
mailu/templates/_helpers.tpl
mailu/templates/_services.tpl
mailu/templates/envvars-configmap.yaml
mailu/templates/tika/deployment.yaml
mailu/templates/tika/service.yaml
mailu/values.yaml

This PR adds a deployment for Tika and allows to set `FULL_TEXT_SEARCH`.
https://mailu.io/2024.06/configuration.html
To enable it, set `tika.enabled` to `true`.
You can change the [languages](https://doc.dovecot.org/settings/plugin/fts-plugin/#fts-languages) to changing the configuration array `tika.languages` (defaults to `en` only).

feat: added Tika support

---

mailu/README.md
mailu/values.yaml

The `mailu-redis-master-0` pod failed to be created when using absolute path `/redis` for redis.master.persistence.subPath. However, removing the leading `/` fixed it.

Fix issue with redis subpath needing to be relative

---

mailu/README.md
mailu/templates/front/service-external.yaml
mailu/values.yaml

fix: Allow setting custom NodePorts for externalService

---

mailu/templates/envvars-configmap.yaml

This PR makes [ingress settings](https://github.com/Mailu/helm-charts/tree/master/mailu#ingress-settings) `ingress.proxyProtocol.*` effective by actually setting the `PROXY_PROTOCOL` environment variable in configmap.
Before that, these settings had no effect at all.

Add PROXY_PROTOCOL environment variable in configmap

---

.github/workflows/publish-chart.yaml

This pull request updates the `.github/workflows/publish-chart.yaml` file to fix paths related to the Helm chart and ensure consistency in the workflow.
* Updated the `helm lint` command to use the correct path `charts/mailu` instead of `mailu`, ensuring the command runs in the appropriate directory.
* Adjusted the `cr package` command to package the Helm chart from the correct path `charts/mailu` instead of `mailu`, aligning with the updated directory structure.

fix: fixed publish pipeline

---

charts/mailu/templates/clamav/statefulset.yaml
charts/mailu/templates/oletools/deployment.yaml
charts/mailu/templates/tika/deployment.yaml
charts/mailu/templates/webdav/deployment.yaml

This pull request updates the way environment variables are injected into several Mailu service templates, improving flexibility and consistency across deployments. The main change is to conditionally include the `envFrom` block only when either a ConfigMap or Secret is specified, and to remove the default reference to a standard ConfigMap. This allows for more granular control of environment variable sources for each service.
**Improvements to environment variable injection:**
* [`charts/mailu/templates/clamav/statefulset.yaml`](diffhunk://#diff-c38dfb712deaac1c54a12e9533d9c3ceee65a23bff5d3bd799608c4030cf4360R89-L91): The `envFrom` block is now only included if either `clamav.extraEnvVarsCM` or `clamav.extraEnvVarsSecret` is set, and the default ConfigMap reference has been removed. …

fix: remove env vars from clamav, oletools and tika pods

---

charts/mailu/ci/helm-lint-values.yaml
charts/mailu/templates/network-policies.yaml

This pull request strengthens network security for the Mailu Helm chart by restricting egress (outbound) internet access for the `tika` and `oletools` components. The changes ensure that these components cannot access the internet unless explicitly allowed, while other components retain their existing egress permissions.
**Network Policy Enhancements:**
* Updated the main network policy to explicitly exclude `tika` and `oletools` pods from unrestricted egress access using `matchExpressions` in the `podSelector`.
* Added two new `NetworkPolicy` resources that deny all egress traffic for pods with the `app.kubernetes.io/component` label set to `tika` and `oletools`, respectively.

fix: restrict tika and oletools internet access

---

charts/mailu/README.md
charts/mailu/values.yaml

This pull request updates the Apache Tika image version used by the Mailu Helm chart from a floating `latest-full` tag to the specific `3.2.2.0-full` tag. This change improves deployment stability by ensuring a consistent Tika version across environments.
Dependency version update:
* Updated the default Tika image tag in `charts/mailu/values.yaml` from `latest-full` to `3.2.2.0-full` to pin the deployed version.
* Updated the documentation in `charts/mailu/README.md` to reflect the new default Tika image tag.

fix: pin tika image to 3.2.2.0-full

---

charts/mailu/Chart.yaml

This pull request updates the `appVersion` in the `charts/mailu/Chart.yaml` file to reflect a newer version of the Mailu application. 
- Bumped the `appVersion` from `2024.06.41` to `2024.06.43` in `Chart.yaml` to track the latest Mailu release.

fix: bump mailu version to 2024.06.43

---

charts/mailu/SETUPS.md
charts/mailu/ci/helm-lint-values.yaml
charts/mailu/templates/tests/test-connection.yaml

- Add test-connection to test availability of the `front` service.

:memo: start documenting setups with the Helm Chart

---

.github/ISSUE_TEMPLATE/bug_report.md

The code block for the `values.yaml` is currently ending after the next heading. Moving the line up to have proper formatting again

fix(github): BUG-issue-template values code block
